# Generated by Django 2.2.6 on 2019-12-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191209_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='goods.Category', verbose_name='所属类别'),
        ),
    ]
