# Generated by Django 2.2.6 on 2019-12-11 07:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20191209_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='商品详情'),
        ),
    ]
