# Generated by Django 2.2.6 on 2019-12-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20191211_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodimage',
            name='index',
            field=models.PositiveIntegerField(default=1, verbose_name='展示顺序'),
        ),
        migrations.AlterField(
            model_name='goodimage',
            name='good_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='goods.Good', verbose_name='商品名'),
        ),
    ]
