# Generated by Django 2.2.6 on 2019-12-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20191211_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodimage',
            name='image',
            field=models.ImageField(upload_to='product/smallImage/%Y/%m/%d', verbose_name='商品图片'),
        ),
    ]
