# Generated by Django 2.2.6 on 2019-12-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20191211_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['id'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='goodimage',
            options={'ordering': ['good_id', 'index'], 'verbose_name': '商品图片', 'verbose_name_plural': '商品图片'},
        ),
    ]
