# Generated by Django 2.2.6 on 2019-12-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20191212_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='零售价'),
        ),
    ]
