# Generated by Django 2.2.6 on 2019-12-16 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0008_auto_20191216_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='导航名称')),
                ('panelId', models.PositiveIntegerField(default=0, verbose_name='面板ID')),
                ('type', models.PositiveIntegerField(default=1, verbose_name='链接类型')),
                ('sortOrder', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('fullUrl', models.CharField(max_length=120, verbose_name='网址链接')),
                ('picUrl', models.CharField(blank=True, max_length=120, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '导航栏类别',
                'verbose_name_plural': '导航栏类别',
                'ordering': ['sortOrder'],
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='板块名称')),
                ('type', models.PositiveIntegerField()),
                ('sort_order', models.PositiveIntegerField(verbose_name='排序')),
                ('position', models.PositiveIntegerField(default=0)),
                ('limit_num', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '首页面板',
                'verbose_name_plural': '首页面板',
            },
        ),
        migrations.CreateModel(
            name='Panelcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField()),
                ('sort_order', models.PositiveIntegerField(verbose_name='排序')),
                ('full_url', models.CharField(blank=True, max_length=120, null=True)),
                ('pic_url', models.CharField(blank=True, max_length=100, null=True)),
                ('pic_url2', models.CharField(blank=True, max_length=100, null=True)),
                ('pic_url3', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('good_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.Good', verbose_name='商品ID')),
                ('panel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='home.Panel', verbose_name='面板ID')),
            ],
            options={
                'verbose_name': '面板内容',
                'verbose_name_plural': '面板内容',
            },
        ),
    ]
