# Generated by Django 2.2.6 on 2019-12-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20191216_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-is_default',), 'verbose_name': '收货地址', 'verbose_name_plural': '收货地址'},
        ),
    ]
