# Generated by Django 2.2.6 on 2019-12-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20191216_1124'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('good_id', 'good_id')},
        ),
    ]
