# Generated by Django 2.2.6 on 2019-12-17 08:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20191216_1124'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_auto_20191217_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='good_num',
            new_name='goodNum',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='good_id',
            new_name='goodid',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('goodid', 'userid')},
        ),
    ]
