# Generated by Django 2.2.6 on 2019-12-17 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20191217_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='goodNum',
            new_name='good_num',
        ),
    ]
