# Generated by Django 2.2.6 on 2019-12-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20191217_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='good_num',
            field=models.PositiveIntegerField(default=0, verbose_name='商品数量'),
        ),
    ]
