# Generated by Django 2.2.6 on 2019-12-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20191217_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='是否被选中'),
        ),
    ]
