# Generated by Django 2.2.6 on 2019-12-19 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0008_auto_20191216_1124'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(default=order.models.get_order_id, editable=False, max_length=30, unique=True, verbose_name='订单号')),
                ('trade_no', models.CharField(max_length=100, unique=True, verbose_name='产品编号')),
                ('pay_status', models.CharField(choices=[('0', '未支付'), ('1', '未发货'), ('2', '已发货'), ('3', '确认收货'), ('4', '已过期'), ('5', '已取消')], default='0', max_length=30, verbose_name='订单状态')),
                ('post_script', models.CharField(blank=True, max_length=200, null=True, verbose_name='附言')),
                ('order_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='订单金额')),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=100, verbose_name='收货信息')),
                ('singer_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('singer_mobile', models.CharField(max_length=11, verbose_name='联系电话')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('close_time', models.DateTimeField(verbose_name='订单完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user_id', to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.PositiveIntegerField(verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='goods.Good', verbose_name='商品名')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.Order', verbose_name='订单')),
            ],
        ),
    ]
