# Generated by Django 2.2.6 on 2019-12-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191219_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_sn',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='订单号'),
        ),
    ]
