# Generated by Django 2.2.6 on 2019-12-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191220_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good', to='goods.Good', verbose_name='商品名'),
        ),
    ]
